### PR TITLE
fix for latest rust

### PR DESCRIPTION
**Pull request by rweichler**

### CODE REVIEW

**Comment by bvssvni** [comment]
Thanks!

**Comment by rweichler** [comment]
BTW, I got rid of passing the Window to update and render. It didn't seem necessary and it caused a compiler error so I just removed that part of the code.

**Comment by bvssvni** [comment]
@rweichler Yeah, I saw that. Nice!

**Comment by rweichler** [comment]
Oh ok. I thought i might have done something bad lol. thanks.

**Pull request merged**
